### PR TITLE
openjdk 11.0.13

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Actions:
1. Update source urls and sha256, 
2. Update home, dev urls
3. Disable `popd` in `build.sh` on `osx`

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Added:
```
  ignore_run_exports:
    - zlib  # [osx]
```

**Comment by skupr-anaconda** [comment]
Added:
```
  binary_relocation: False
  detect_binary_files_with_prefix: False
```
But I'm not sure if it's correct to use them

**Comment by skupr-anaconda** [comment]
Added:
```
missing_dso_whitelist:
    - $RPATH/libz.so.1
    - $RPATH/libjli.so
    - $RPATH/libjvm.so
    - $RPATH/libfreetype.so.6
    - $RPATH/libgobject-2.0.so.0
    - $RPATH/libglib-2.0.so.0
    - $RPATH/libnss3.so
    - $RPATH/libdrm.so.2
    - $RPATH/libgbm.so.1
    - $RPATH/libnssutil3.so
    - $RPATH/libsmime3.so
    - $RPATH/libnspr4.so
    - $RPATH/libatk-1.0.so.0
    - $RPATH/libatk-bridge-2.0.so.0
    - $RPATH/libexpat.so.1
    - $RPATH/libxcb.so.1
    - $RPATH/libgio-2.0.so.0
    - $RPATH/libxkbcommon.so.0
    - $RPATH/libdbus-1.so.3
    - $RPATH/libX11.so.6
    - $RPATH/libXcomposite.so.1
    - $RPATH/libXdamage.so.1
    - $RPATH/libXext.so.6
    - $RPATH/libXfixes.so.3
    - $RPATH/libXrandr.so.2
    - $RPATH/libasound.so.2
    - $RPATH/libcups.so.2
    - $RPATH/libatspi.so.0
    - $RPATH/libxshmfence.so.1
    - $RPATH/libjawt.so
    - $RPATH/libXrender.so.1
    - $RPATH/libXtst.so.6
    - $RPATH/libXi.so.6
    - $RPATH/libXxf86vm.so.1
    - $RPATH/libXcursor.so.1
    - $RPATH/libstdc++.so.6
    - $RPATH/libjvm.dylib  # [osx]
    - $RPATH/libjawt.dylib  # [osx]
```

**Comment by skupr-anaconda** [comment]
Fixed tests

**Comment by skupr-anaconda** [comment]
An error onlinux-aarch64:
```
Error: dl failure on line 635

Error: failed /opt/conda/conda-bld/openjdk_1641289608986/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/server/libjvm.so, because /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/conda/conda-bld/openjdk_1641289608986/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/server/libjvm.so)
```

**Comment by skupr-anaconda** [comment]
An error on osx-arm64:
`['  ERROR (openjdk,lib/libjcef.dylib): /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/croot-_5ro4shq/openjdk_1641290515533/Frameworks/JavaNativeFoundation.framework/JavaNativeFoundation not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']`

**Comment by skupr-anaconda** [comment]
Added to `missing_dso_whitelist`::
```
    - Library\bin\VCRUNTIME140.dll      # [win]
    - Library\bin\bin\VCRUNTIME140.dll  # [win]
    - Library\bin\MSVCP140.dll          # [win]
    - Library\bin\bin\MSVCP140.dll      # [win]
    - $RPATH/jvm.dll                    # [win]
```

**Comment by skupr-anaconda** [comment]
Skip building on `aarch64 `for now

**Comment by skupr-anaconda** [comment]
Skip building on `s390x `or `ppc64le`.

**Review by tobijk — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
Updated `host `and `run`:
```
  host:
    - zlib                    # [unix]
    - expat                   # [linux]
    - dbus                    # [linux]
    - freetype                # [linux]
    - pango                   # [linux and aarch64]
    - cairo                   # [linux and aarch64]
    - glib                    # [linux]
    - libxcb                  # [linux]
  run:
    - expat                   # [linux]
    - dbus                    # [linux]
    - freetype                # [linux]
    - pango                   # [linux and aarch64]
    - cairo                   # [linux and aarch64]
    - glib                    # [linux]
    - libxcb                  # [linux]
```

**Comment by skupr-anaconda** [comment]
Updated `ignore_run_exports`:
```
ignore_run_exports:
    - zlib               # [osx]
    - expat              # [linux]
    - dbus               # [linux]
    - freetype           # [linux]
    - pango              # [linux and aarch64]
    - cairo              # [linux and aarch64]
```

**Comment by skupr-anaconda** [comment]
I reordered dependencies alphabetically

**Pull request merged**
